# Generated by Django 2.2.1 on 2019-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=50000)),
                ('author', models.CharField(max_length=100)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('timelimit', models.IntegerField()),
                ('codelimit', models.IntegerField()),
            ],
        ),
    ]
