# Generated by Django 2.2.1 on 2019-05-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackGround', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.FloatField()),
                ('input', models.CharField(max_length=50000)),
                ('output', models.CharField(max_length=50000)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codetype', models.FloatField()),
                ('code', models.CharField(max_length=50000)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('cost', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='cost',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackGround.User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='codelimit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='issue',
            name='timelimit',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SubmitCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ispass', models.BooleanField()),
                ('cost', models.FloatField(default=100.0)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('checkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackGround.Check')),
                ('submitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackGround.Submit')),
            ],
        ),
        migrations.AddField(
            model_name='submit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackGround.User'),
        ),
    ]
