# Generated by Django 2.2.1 on 2019-05-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackGround', '0002_auto_20190527_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='author',
        ),
    ]
