# Generated by Django 2.2.1 on 2019-05-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackGround', '0003_auto_20190527_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BackGround.User'),
        ),
        migrations.AddField(
            model_name='submit',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BackGround.User'),
        ),
    ]
