# Generated by Django 2.2.1 on 2019-05-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackGround', '0004_auto_20190527_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='issue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BackGround.Issue'),
        ),
    ]
